apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-api-page
data:
  index.html: |
    <html>
    <body>
      <h1>Backend API endpoint</h1>
      <p>This is a test response from /api</p>
    </body>
    </html>
